# PORTABLE CHESTS
# Copyright Max Rumsey - 2020
#
# Example Config:
# SQLite:
#  Filename: 'database'
#
# Chests:
#  vault: <-- Name of chest
#    rows: 5 <-- Rows available
#    name: "Your vault!" <-- Name of the chest in the GUI
#    permission-denied: "Sorry, you do not have permission to access this chest." <-- Permission-denied message
#
# default:
#  rows: 5 <-- Default rows of each chest
#  name: "Portable Chest" <-- Default Name of Chest
#  permission-denied: "Sorry, you do not have permission to access this chest." <-- Default permission denied message

SQLite:
  Filename: 'database'

Chests:
  vault:
    rows: 5
    name: "Your vault!"
    permission-denied: "Sorry, you do not have permission to access this chest."

default:
  rows: 5
  name: "Portable Chest"
  permission-denied: "Sorry, you do not have permission to access this chest."