# Settings for the SQLite DB, just leave as normal for now.

# DEFAULT:
# SQLite:
#   Filename: 'database'
SQLite:
  Filename: 'database'

Chests:
  vault:
    rows: 5
    name: "Your vault!"
    permission-denied: "Sorry, you do not have permission to access this vault."
