name: PortableChests
version: "2.0.0"
main: xyz.maxrumsey.portablechests.PortableChests
api-version: "1.13"
authors: [ExiFlame]
description: A bukkit plugin that allows users to have virtual chests, opened by command.
website: https://www.maxrumsey.xyz

permissions:
  PortableChests.*:
    children:
      PortableChests.chest: true
      PortableChests.inspect: true
  PortableChests.chest:
    description: Allows access to the /chest command
  PortableChests.inspect:
    description: Allows access to the /inspect command
  PortableChests.admin:
    description: Allows access to the /setchest command

commands:
  chest:
    description: "Open the specified chest."
    usage: "Syntax error. Usage: /<command> <chest_name>"
  inspect:
    description: "Opens the specified chest of the specified user."
    usage: "Syntax error. Usage: /<command> <user> <chest_name>"
  chestconfig:
    description: "Updates the configuration of a specific chest"
    usage: "Syntax error. Usage: /<command> help"
    permission: "PortableChests.admin"